apiVersion: apps/v1
kind: Deployment
metadata:
  name: betvictor-app-deployment
  labels:
    app: betvictor
spec:
  replicas: 6
  selector:
    matchLabels:
      app: betvictor
  template:
    metadata:
      labels:
        app: betvictor
    spec:
      containers:
        - name: betvictor
          image: 793380206298.dkr.ecr.eu-west-1.amazonaws.com/betvictor_ecr:betvictor_application_image
          ports:
            - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: betvictor-service
spec:
  type: LoadBalancer
  selector:
    app: betvictor
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000