apiVersion: apps/v1
kind: Deployment
metadata:
  name: betvictor-app-deployment
  labels:
    app: betvictor
spec:
  selector:
    matchLabels:
      app: betvictor
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: betvictor
    spec:
      containers:
        - name: betvictor
          image: 793380206298.dkr.ecr.eu-west-1.amazonaws.com/betvictor_ecr:${{ github.sha }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 0.25
            limits:
              cpu: 0.3

---

apiVersion: v1
kind: Service
metadata:
  name: betvictor-lb-service
spec:
  type: LoadBalancer
  selector:
    app: betvictor
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---

#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: betvictor-HPA
#  namespace: default
#spec:
#  targetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: betvictor
#  behavior:
#    scaleDown:
#      policies:
#        - type: Pods
#          value: 2
#        - type: Percent
#          value: 30
#      selectPolicy: Min
#      stabilizationWindowSeconds: 300
#    scaleUp:
#      policies:
#        - type: Pods
#          value: 6
#        - type: Percent
#          value: 75
#      selectPolicy: Max
#      stabilizationWindowSeconds: 0
